// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvmdbqbhzmofbqqelyfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2bWRicWJoem1vZmJxcWVseWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODg3ODgsImV4cCI6MjA3MjU2NDc4OH0.usY2jN3UELDldTG3-s_AEWzMtcL42syWs04-I8TsBSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});